### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AllCheeks** [chocopie69/Minecraft-Modifications-Codes#1]
[17:50:13] [Client thread/INFO]: Setting user: Player419
[17:50:13] [Client thread/INFO]: (Session ID is token:0:Player419)
Exception in thread "Client thread" java.lang.NullPointerException
	at net.minecraft.crash.CrashReport.populateEnvironment(CrashReport.java:145)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
	at net.minecraft.crash.CrashReport.makeCrashReport(CrashReport.java:418)
	at net.minecraft.client.Minecraft.run(Minecraft.java:439)
	at net.minecraft.client.main.Main.main(Main.java:113)
	at Start.main(Start.java:11)
[17:50:14] [Client Shutdown Thread/INFO]: Stopping server
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by AllCheeks** [comment]
> are you retarded

i m a rookie
can you tell me how to solve this mentally retarded problem XD

**Comment by AcaiBerii** [comment]
First, please provide context.

1. What version of MCP or Forge are you using? - Follow ```1.8.9-xxxx.xxxx.etc``` for forge, ```1.8.8-xxx``` for MCP.

2. What client are you trying to run? - Fan, Fan v4, Sigma, FusionX?

3. Look at the stacktrace - Not familiar with it? Look at https://stackify.com/java-stack-trace/ for help. Look through the source code for each thing causing the crash.

4. Please remember that this is mainly for source code only, not running. In other words, you are stupid.

**Comment by Ali00035** [comment]
> are you retarded

sup callcum

**Comment by CodeManDev** [comment]
> 
> 
> are you retarded

callum what are you doing here
